name: Docker Image CI

on:
  push:
    paths:
    - 'Src/**'
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build . --file Dockerfile --tag nagerat/nager-date:$GITHUB_BASE_REF-$GITHUB_RUN_NUMBER --tag nagerat/nager-date:latest
        docker push nagerat/nager-date:$GITHUB_BASE_REF-$GITHUB_RUN_NUMBER
        docker push nagerat/nager-date:latest
        
